#!/bin/bash

##
## SNAPRAID
##
## https://www.snapraid.it

# require for build
apt install gcc git make -y

wget https://github.com/amadvance/snapraid/releases/download/v12.2/snapraid-12.2.tar.gz
tar xzvf snapraid-12.2.tar.gz
cd snapraid-12.2/
./configure
make
make check
make install
cd ..
cp ~/snapraid-12.2/snapraid.conf.example /etc/snapraid.conf
cd ..

echo "cleanup..."
rm -rf snapraid*

echo "repair disk you want to use with file system you want to like ext4 for xfs"
echo

echo "create data disk mount directories"
mkdir -p /mnt/data/{disk1,disk2,disk3,disk4}
echo "Create parity disk mount directories"
mkdir -p /mnt/parity/1-parity

echo "list of disk by id"
ls -la /dev/disk/by-id/ | grep part1  | cut -d " " -f 11-20

echo "mount it in /etc/fstab"
# # SnapRAID Disks
# /dev/disk/by-id/ata-HGST_HDN724040ALE640_PK2334PBHDYY0R-part1 /mnt/data/disk1 ext4 defaults 0 2
# /dev/disk/by-id/ata-HGST_HDS5C4040ALE630_PL2331LAG90YYJ-part1 /mnt/data/disk2 ext4 defaults 0 2
# /dev/disk/by-id/ata-HGST_HUS726060ALA640_AR31001EG1YE8C-part1 /mnt/data/disk3 ext4 defaults 0 2
# /dev/disk/by-id/ata-Hitachi_HDS5C3030ALA630_MJ0351YNYYYK9A-part1 /mnt/data/disk4 ext4 defaults 0 2
# # Parity Disks
# /dev/disk/by-id/ata-Hitachi_HDS5C3030ALA630_MJ1313YNGYYYJC-part1 /mnt/parity/1-parity ext4 defaults 0 2

echo "change snapraid configuration"
# nano /etc/snapraid.conf
# parity /mnt/parity/1-parity/snapraid.parity
# Or multi parity files setup
# parity /mnt/split-parity/parity1-disk1/part1.parity,/mnt/split-parity/parity1-disk2/part2.parity
# 2-parity /mnt/split-parity/parity2-disk1/part1.parity,/mnt/split-parity/parity2-disk2/part2.parity
# readmore: 7.2 (2,3,4,5,6)-parity FILE [,FILE] ... https://www.snapraid.it/manual
# #
# content /var/snapraid/content
# content /mnt/data/disk1/content
# content /mnt/data/disk2/content
# content /mnt/data/disk3/content
# content /mnt/data/disk4/content
# #
# disk d1 /mnt/data/disk1/
# disk d2 /mnt/data/disk2/
# disk d3 /mnt/data/disk3/
# disk d4 /mnt/data/disk4/
# #
# exclude *.bak
# exclude *.unrecoverable
# exclude /tmp/
# exclude /lost+found/
# exclude .AppleDouble
# exclude ._AppleDouble
# exclude .DS_Store
# exclude .Thumbs.db
# exclude .fseventsd
# exclude .Spotlight-V100
# exclude .TemporaryItems
# exclude .Trashes
# exclude .AppleDB
# #
# block_size 256

echo "create directory to save content file in local path, too.../var/snapraid/"
mkdir -p /var/snapraid/

##
## MergerFS to merge content of multiply disks to one mount point for easy access and managerment
##
# https://www.linuxserver.io/user/pages/content/images/2016/09/mergerfs.png

apt-get install g++ pkg-config git git-buildpackage pandoc debhelper libfuse-dev libattr1-dev -y
git clone https://github.com/trapexit/mergerfs.git 
cd mergerfs
make clean
make deb
cd ..
dpkg -i mergerfs*_amd64.deb
rm mergerfs*_amd64.deb mergerfs*_amd64.changes mergerfs*.dsc mergerfs*.tar.gz

echo "adding config to /etc/fstab. note: dont use cache.files=off - it's stop backup file from proxmox"
# /mnt/data/* /mnt/storage fuse.mergerfs threads=12,allow_other,use_ino,dropcacheonclose=true,category.create=mfs,moveonenospc=true,minfreespace=20G,fsname=mergerfsPool,nonempty 0 0
mdkir -p /mnt/storage


## REFS
# https://zackreed.me/setting-up-snapraid-on-ubuntu/
# https://zackreed.me/snapraid-split-parity-sync-script/
# https://www.linuxserver.io/blog/2017-06-24-the-perfect-media-server-2017
